# **PYTHON PROJECT 1**
Newton Ndiwa

### **Importing pandas and numpy libraries**

In [24]:
import pandas as pd
import numpy as np

In [27]:
df_1=pd.read_csv('//content//anime_ratings_data - Copy.csv')
df_1

,title,mediaType,eps,duration,startYr,finishYr,description,contentWarn,watched,watching,rating,votes,studio_primary,studios_colab,genre
0,Dragon Ball Z Movie 15: Resurrection 'F',Movie,1,67.0,2015,2015,Even the complete obliteration of his physical...,No,4649,86,3.979,3100.0,Toei Animation,No,Other
1,Kuripuri*Kuripura,Movie,1,5.0,2008,2008,NaN,No,10,0,2.120,10.0,Others,No,Other
2,GJ-bu@,TV Special,1,46.0,2014,2014,The story is set during the spring vacation im...,No,1630,16,3.758,1103.0,Others,No,Other
3,Nausicaa of the Valley of the Wind,Movie,1,67.0,1984,1984,One thousand years after the Giant Warriors ca...,No,4649,184,4.444,3100.0,Others,No,Drama
4,Miru Tights Special,DVD Special,1,4.0,2019,2019,Yua is asked to model an illustrator's designs...,No,346,8,2.494,234.0,Others,No,Other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6518,"Watamote: No Matter How I Look at It, It's You...",TV,12,5.0,2013,2013,"Tomoko Kuroki is eager to begin her new, glamo...",No,4649,199,3.633,3100.0,Others,No,Other
6519,Eight Clouds Rising,OVA,2,44.5,1997,1997,Kuraki has taken his grandfatherâ€™s ancient swo...,No,341,9,2.573,208.0,Studio Pierrot,No,Other
6520,Ishifuro: Ryuu no Tani to Taiyou no Toride,Music Video,1,4.0,2016,2016,NaN,No,25,0,1.749,14.0,Others,No,Other
6521,Sword Art Online: Alicization,TV,24,7.5,2018,2019,"Kirito awakens in a vast, fantastical forest f...",Yes,4649,199,4.145,3100.0,A-1 Pictures,No,Other
6522,xxxHOLiC Kei,TV,13,12.0,2008,2008,"Watanuki, who is able to see the spirit world,...",No,4649,199,4.399,3100.0,Production I.G,No,Other

In [32]:
df_2=pd.read_csv(r'/content/anime_ratings_data - Copy.csv')
df_2

,title,mediaType,eps,duration,startYr,finishYr,description,contentWarn,watched,watching,rating,votes,studio_primary,studios_colab,genre
0,Dragon Ball Z Movie 15: Resurrection 'F',Movie,1,67.0,2015,2015,Even the complete obliteration of his physical...,No,4649,86,3.979,3100.0,Toei Animation,No,Other
1,Kuripuri*Kuripura,Movie,1,5.0,2008,2008,NaN,No,10,0,2.120,10.0,Others,No,Other
2,GJ-bu@,TV Special,1,46.0,2014,2014,The story is set during the spring vacation im...,No,1630,16,3.758,1103.0,Others,No,Other
3,Nausicaa of the Valley of the Wind,Movie,1,67.0,1984,1984,One thousand years after the Giant Warriors ca...,No,4649,184,4.444,3100.0,Others,No,Drama
4,Miru Tights Special,DVD Special,1,4.0,2019,2019,Yua is asked to model an illustrator's designs...,No,346,8,2.494,234.0,Others,No,Other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6518,"Watamote: No Matter How I Look at It, It's You...",TV,12,5.0,2013,2013,"Tomoko Kuroki is eager to begin her new, glamo...",No,4649,199,3.633,3100.0,Others,No,Other
6519,Eight Clouds Rising,OVA,2,44.5,1997,1997,Kuraki has taken his grandfatherâ€™s ancient swo...,No,341,9,2.573,208.0,Studio Pierrot,No,Other
6520,Ishifuro: Ryuu no Tani to Taiyou no Toride,Music Video,1,4.0,2016,2016,NaN,No,25,0,1.749,14.0,Others,No,Other
6521,Sword Art Online: Alicization,TV,24,7.5,2018,2019,"Kirito awakens in a vast, fantastical forest f...",Yes,4649,199,4.145,3100.0,A-1 Pictures,No,Other
6522,xxxHOLiC Kei,TV,13,12.0,2008,2008,"Watanuki, who is able to see the spirit world,...",No,4649,199,4.399,3100.0,Production I.G,No,Other

### **Loading the dataset**

In [50]:
df=pd.read_csv("/content/drive/MyDrive/Ndiwa/anime_ratings_data - Copy.csv")
#Reading the first five records
df.head(5)

,title,mediaType,eps,duration,startYr,finishYr,description,contentWarn,watched,watching,rating,votes,studio_primary,studios_colab,genre
0,Dragon Ball Z Movie 15: Resurrection 'F',Movie,1,67.0,2015,2015,Even the complete obliteration of his physical...,No,4649,86,3.979,3100.0,Toei Animation,No,Other
1,Kuripuri*Kuripura,Movie,1,5.0,2008,2008,NaN,No,10,0,2.120,10.0,Others,No,Other
2,GJ-bu@,TV Special,1,46.0,2014,2014,The story is set during the spring vacation im...,No,1630,16,3.758,1103.0,Others,No,Other
3,Nausicaa of the Valley of the Wind,Movie,1,67.0,1984,1984,One thousand years after the Giant Warriors ca...,No,4649,184,4.444,3100.0,Others,No,Drama
4,Miru Tights Special,DVD Special,1,4.0,2019,2019,Yua is asked to model an illustrator's designs...,No,346,8,2.494,234.0,Others,No,Other

In [2]:
#Reading the last five rows of the dataset
df.tail(5)

,title,mediaType,eps,duration,startYr,finishYr,description,contentWarn,watched,watching,rating,votes,studio_primary,studios_colab,genre
6518,"Watamote: No Matter How I Look at It, It's You...",TV,12,5.0,2013,2013,"Tomoko Kuroki is eager to begin her new, glamo...",No,4649,199,3.633,3100.0,Others,No,Other
6519,Eight Clouds Rising,OVA,2,44.5,1997,1997,Kuraki has taken his grandfatherâ€™s ancient swo...,No,341,9,2.573,208.0,Studio Pierrot,No,Other
6520,Ishifuro: Ryuu no Tani to Taiyou no Toride,Music Video,1,4.0,2016,2016,NaN,No,25,0,1.749,14.0,Others,No,Other
6521,Sword Art Online: Alicization,TV,24,7.5,2018,2019,"Kirito awakens in a vast, fantastical forest f...",Yes,4649,199,4.145,3100.0,A-1 Pictures,No,Other
6522,xxxHOLiC Kei,TV,13,12.0,2008,2008,"Watanuki, who is able to see the spirit world,...",No,4649,199,4.399,3100.0,Production I.G,No,Other

In [3]:
#Sampling the first 10 rows of the dataset
df.head(10)

,title,mediaType,eps,duration,startYr,finishYr,description,contentWarn,watched,watching,rating,votes,studio_primary,studios_colab,genre
0,Dragon Ball Z Movie 15: Resurrection 'F',Movie,1,67.0,2015,2015,Even the complete obliteration of his physical...,No,4649,86,3.979,3100.0,Toei Animation,No,Other
1,Kuripuri*Kuripura,Movie,1,5.0,2008,2008,NaN,No,10,0,2.120,10.0,Others,No,Other
2,GJ-bu@,TV Special,1,46.0,2014,2014,The story is set during the spring vacation im...,No,1630,16,3.758,1103.0,Others,No,Other
3,Nausicaa of the Valley of the Wind,Movie,1,67.0,1984,1984,One thousand years after the Giant Warriors ca...,No,4649,184,4.444,3100.0,Others,No,Drama
4,Miru Tights Special,DVD Special,1,4.0,2019,2019,Yua is asked to model an illustrator's designs...,No,346,8,2.494,234.0,Others,No,Other
5,Da Capo Second Season,TV,26,5.0,2005,2005,"Hatsune-Jima, a city once known for their ever...",No,4649,187,3.520,3100.0,Others,No,Other
6,WWF 100% Renewable Energy,Web,1,3.0,2012,2012,This film was made for the campaign for using ...,No,20,1,1.875,10.0,Others,No,Other
7,Tayo the Little Bus,TV,26,11.0,2010,2010,Tayo the Little BusÂ is about exciting adventur...,No,19,0,1.938,14.0,Others,No,Other
8,Ai no Kusabi,OVA,2,50.0,1992,1994,"On the planet Amoi, a great society has develo...",Yes,4155,100,3.340,2633.0,Others,No,Other
9,Is It Wrong to Try to Pick Up Girls in a Dungeon?,TV,13,6.0,2015,2015,Is It Wrong to Try and Pick Up Girls in a Dung...,No,4649,199,4.280,3100.0,J.C. Staff,No,Other

In [4]:
#Getting general infomation about the structure of the dataset
df.info

<bound method DataFrame.info of                                                   title    mediaType  eps  \
0              Dragon Ball Z Movie 15: Resurrection 'F'        Movie    1
1                                     Kuripuri*Kuripura        Movie    1
2                                                GJ-bu@   TV Special    1
3                    Nausicaa of the Valley of the Wind        Movie    1
4                                   Miru Tights Special  DVD Special    1
...                                                 ...          ...  ...
6518  Watamote: No Matter How I Look at It, It's You...           TV   12
6519                                Eight Clouds Rising          OVA    2
6520         Ishifuro: Ryuu no Tani to Taiyou no Toride  Music Video    1
6521                      Sword Art Online: Alicization           TV   24
6522                                       xxxHOLiC Kei           TV   13

      duration  startYr  finishYr  \
0         67.0     2015      2015
1          5.0     2008      2008
2         46.0     2014      2014
3         67.0     1984      1984
4          4.0     2019      2019
...        ...      ...       ...
6518       5.0     2013      2013
6519      44.5     1997      1997
6520       4.0     2016      2016
6521       7.5     2018      2019
6522      12.0     2008      2008

                                            description contentWarn  watched  \
0     Even the complete obliteration of his physical...          No     4649
1                                                   NaN          No       10
2     The story is set during the spring vacation im...          No     1630
3     One thousand years after the Giant Warriors ca...          No     4649
4     Yua is asked to model an illustrator's designs...          No      346
...                                                 ...         ...      ...
6518  Tomoko Kuroki is eager to begin her new, glamo...          No     4649
6519  Kuraki has taken his grandfatherâ€™s ancient swo...          No      341
6520                                                NaN          No       25
6521  Kirito awakens in a vast, fantastical forest f...         Yes     4649
6522  Watanuki, who is able to see the spirit world,...          No     4649

      watching  rating   votes  studio_primary studios_colab  genre
0           86   3.979  3100.0  Toei Animation            No  Other
1            0   2.120    10.0          Others            No  Other
2           16   3.758  1103.0          Others            No  Other
3          184   4.444  3100.0          Others            No  Drama
4            8   2.494   234.0          Others            No  Other
...        ...     ...     ...             ...           ...    ...
6518       199   3.633  3100.0          Others            No  Other
6519         9   2.573   208.0  Studio Pierrot            No  Other
6520         0   1.749    14.0          Others            No  Other
6521       199   4.145  3100.0    A-1 Pictures            No  Other
6522       199   4.399  3100.0  Production I.G            No  Other

[6523 rows x 15 columns]>

In [5]:
#Describing the number of features and records of the dataset
print('The dataset has',df.columns.shape, 'columns and', df.index.shape,'records')

The dataset has (15,) columns and (6523,) records

In [6]:
#Diplaying the column data types
df.dtypes

title              object
mediaType          object
eps                 int64
duration          float64
startYr             int64
finishYr            int64
description        object
contentWarn        object
watched             int64
watching            int64
rating            float64
votes             float64
studio_primary     object
studios_colab      object
genre              object
dtype: object

### **Measures of Central Tendency**

In [17]:
#Selecting columns with numerical data types
df_num=df.select_dtypes(np.number)
#getting the statistical description of the numerical columns of the data set
df_num.describe()

,eps,duration,startYr,finishYr,watched,watching,rating,votes
count,6523.000000,6248.000000,6523.000000,6523.000000,6523.000000,6523.000000,6523.000000,6496.000000
mean,8.716235,18.396287,2005.241147,2005.575349,1347.948643,57.445654,2.962553,906.253233
std,11.002479,20.949350,12.911035,12.568169,1737.138112,76.527405,0.760486,1171.677648
min,1.000000,1.000000,1967.000000,1970.000000,5.000000,0.000000,1.111000,10.000000
25%,1.000000,5.000000,2000.000000,2000.000000,56.000000,2.000000,2.371000,34.000000
50%,1.000000,7.000000,2010.000000,2010.000000,349.000000,13.000000,2.944000,227.500000
75%,12.000000,25.000000,2015.000000,2015.000000,2252.500000,98.000000,3.568000,1567.750000
max,34.000000,67.000000,2020.000000,2020.000000,4649.000000,199.000000,4.702000,3100.000000

In [51]:
#Changing the object dtypes to categorical data
df_cat=df[['mediaType', 'contentWarn','studio_primary', 'studios_colab', 'genre']].astype('category')
#Describing the categorical columns
df_cat.describe()

       mediaType contentWarn studio_primary studios_colab  genre
count       6496        6523           6523          6523   6523
unique         8           2             11             2      9
top           TV          No         Others            No  Other
freq        2145        5825           4684          6210   5468